<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="2" time="0.030"><testcase classname="test_4.TestClass" file="test_4.py" line="4" name="test_one" time="0.000409841537476"></testcase><testcase classname="test_4.TestClass" file="test_4.py" line="8" name="test_two" time="0.00252509117126"><failure message="assert &apos;hello&apos; == &apos;hi&apos;
  - hello
  + hi">self = &lt;test_4.TestClass object at 0xc1fab0&gt;

    def test_two(self):
        x = &quot;hello&quot;
&gt;       assert x == &quot;hi&quot;
E       assert &apos;hello&apos; == &apos;hi&apos;
E         - hello
E         + hi

test_4.py:11: AssertionError</failure></testcase></testsuite>